version: '3.8'
services:  
  mongodb:
    container_name: mongodb
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - sentiment-analyzer-api-network

volumes:
  mongo-data:
    name: sentiment-analyzer-api-db-data
networks:
  sentiment-analyzer-api-network:
    name: sentiment-analyzer-api-backend-network
    driver: bridge